### ISSUE TITLE
StackOverflowError - Could not pass event EntityDamageByEntityEvent to Cannons

### ISSUE THREAD

**Issue by TomLewis** [TylerS1066/Movecraft-Cannons#15] opened 2022-01-28 22:22 UTC
So we had a user spam killed in our chat, which we have never seen before in 9 years! Always great to see something new!
https://i.imgur.com/0OMAwXT.png

Which turned up a Cannons/Movecraft-Cannons error in the log, the reason we know it was  Movecraft-Cannons is the way he described what happened:
https://i.imgur.com/UUquqmn.png

> When you fire a cannon forwards while moving

https://gist.github.com/TomLewis/db7037e6f3df915f8da3608b5248de75

Turns out this players put /cruise on a hotkey and spammed it like 1000 times while firing a ship!?

**Comment by galacticwarrior9** [comment] 2022-01-29 01:19
IIRC, the problem here is solely on Cannons' side. It is not related to Movecraft-Cannons. I experienced the same issue on my server and fixed it [like this](https://github.com/CCNetMC/Cannons/commit/164807f75851ef61dea0eaf20ce3b37361e4881d).

**Comment by TylerS1066** [comment] 2022-01-29 01:44
Thanks so much @galacticwarrior9!  Do you have a dev build or release that @TomLewis can try to verify the issue is solved?  If so, are you planning on submitting a PR to upstream cannons to fix the problem?

I'm going to close this issue, but feel free to continue discussing the problem here.

**Closed as completed by TylerS1066** 2022-01-29 01:44 UTC

**Comment by TomLewis** [comment] 2022-01-29 12:42
Amazing! Thanks @galacticwarrior9 I'm glad someone else had it and already fixed it! Has your fix been pushed up stream to the main cannons repo?

@DerPavlov

**Comment by galacticwarrior9** [comment] 2022-01-30 15:00
Fix has been merged upstream ^
